#!/bin/sh

. /etc/forban.common

/etc/init.d/forban enable
/etc/init.d/forban init
/etc/init.d/forban update


forban_install_rclocal

#Disable Watchdog.
/etc/init.d/watchdog disable

/etc/init.d/forban start
